monolog:
    handlers:
        sentry:
            type:  raven
            dsn:   '%env(SENTRY_DSN)%'
            level: error
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
            process_psr_3_messages: false
            verbosity_levels:
                VERBOSITY_NORMAL: INFO
                VERBOSITY_VERBOSE: DEBUG
            channels: ['!event', '!doctrine']